🧹  Improving openssl policy
mondoohq/cnspec-policies pull request #393
Opened 2024-05-08 09:34 UTC by HRouhani

2024-05-08 11:10 UTC, chris-rock requested changes

2024-05-08 11:10 UTC, chris-rock commented on core/mondoo-openssl-vulnerability.mql.yaml
> +      semver(package("openssl").version) < semver("3.0.0") ||
That check is not correct.

2024-05-08 11:10 UTC, chris-rock commented on core/mondoo-openssl-vulnerability.mql.yaml
> +          semver(package("openssl").version) > semver("3.0.6")
that check is not correct

2024-05-10 14:38 UTC, mm-weber approved these changes
LGTM

2024-05-10 14:41 UTC, chris-rock approved these changes

2024-05-10 14:41 UTC, merged